# syntax=docker/dockerfile:1
FROM registry.suse.com/bci/nodejs:22 AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM dp.apps.rancher.io/containers/nginx:1.31 AS final
COPY image-build/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/build /srv/www/htdocs
RUN chmod -R a+rX /srv/www/htdocs
EXPOSE 8080
USER 10001
CMD ["nginx", "-g", "daemon off;"]