name: staging-build

on:
  push:
    branches:
      - staging

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build images
        id: build
        run: |
          VERSION=$(git rev-parse --short "$GITHUB_SHA")
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          docker buildx create --name multiarch --driver docker-container --use
          docker buildx build --platform linux/amd64 -f image-build/Containerfile --push -t ghcr.io/${{ github.repository }}:$VERSION .

      - name: Checkout ssf-actions
        uses: actions/checkout@v4
        with:
          repository: atoy3731/ssf-actions
          path: ssf-actions
          token: ${{ secrets.SSF_ACTIONS_READ_PAT }}

      - name: Update hauler-docs image tag in ssf
        uses: ./ssf-actions/update-yaml-value
        with:
          repository: ${{ secrets.UPDATE_REPO }}
          file-path: fleet/public-cluster/hauler-docs/values.yaml
          yaml-path: .image.tag
          value: ${{ steps.build.outputs.version }}
          ssh-deploy-key: ${{ secrets.UPDATE_KEY }}